services:
  app:
    build: .
    container_name: d-id_next
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
    volumes:
      - ./public/uploads:/app/public/uploads
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    build: .
    container_name: d-id_cron_worker
    restart: always
    env_file: .env
    command: ["npx", "tsx", "scripts/cron/knowledge-worker.ts"]
    volumes:
      - ./public/uploads:/app/public/uploads
    depends_on:
      - app
      - redis
      - postgres


  postgres:
    image: postgres:18.1
    container_name: d-id_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql
    ports:
      - '5432:5432'
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}' ]
      interval: 10s
      timeout: 5s
      retries: 5
    mem_limit: 2g
    mem_reservation: 1g

  redis:
    image: redis:8-alpine
    container_name: d-id_redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  external_sources_cron:
    image: alpine:3.18
    container_name: d-id_external_sources_cron
    depends_on:
      - app
    environment:
      APP_BASE_URL: "http://app:3000"
      CRON_SECRET: ${CRON_SECRET}
    volumes:
      - ./scripts/cron/setup-cron.sh:/setup-cron.sh
    command: ["sh", "/setup-cron.sh"]
    restart: unless-stopped

volumes:
  redis_data:
  pg_data:
