import type { Metadata } from "next";
import "./globals.css";
import Local from "next/font/local";

const nasalization = Local({
  src: "../assets/fonts/Nasalization_regular.otf",
  variable: "--font-nasalization-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nasalization.variable}`}>{children}</body>
    </html>
  );
}
